name: c8e9ee244b1c587087b5376ce614d3ea
on:
  workflow_dispatch:
  schedule:
    - cron: '21 1 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.JD_REPO_NAME }}
          ref: ${{ secrets.JD_REPO_BRANCH }}
          token: ${{ secrets.PAT }}
      - name: Checkout ss
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.SCRIPTS_PATH }}
          token: ${{ secrets.SCRIPTS_PAT }}
          ref: master
          path: ss
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - name: npm install
        run: |
          npm install
      - name: update script
        run: |
          rm -rf .git
          rm -rf .github
          python3 ss/jd/update_jd_scripts.py
      - name: '运行 【c8e9ee244b1c587087b5376ce614d3ea】'
        run: |
          node jd_rankingList.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE}}
          JD_DEBUG: ${{ secrets.JD_DEBUG}}
          JD_USER_AGENT: ${{ secrets.JD_USER_AGENT}}
          TENCENTSCF_SOURCE_TYPE: ${{ secrets.TENCENTSCF_SOURCE_TYPE}}
          TENCENTSCF_SOURCE_URL: ${{ secrets.TENCENTSCF_SOURCE_URL}}
          PUSH_KEY: ${{ secrets.PUSH_KEY}}
          BARK_PUSH: ${{ secrets.BARK_PUSH}}
          BARK_SOUND: ${{ secrets.BARK_SOUND}}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN}}
          TG_USER_ID: ${{ secrets.TG_USER_ID}}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN}}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET}}
          QYWX_KEY: ${{ secrets.QYWX_KEY}}
          IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY}}
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN}}
          PUSH_PLUS_USER: ${{ secrets.PUSH_PLUS_USER}}
          TG_PROXY_HOST: ${{ secrets.TG_PROXY_HOST}}
          TG_PROXY_PORT: ${{ secrets.TG_PROXY_PORT}}
          FRUITSHARECODES: ${{ secrets.FRUITSHARECODES}}
          PETSHARECODES: ${{ secrets.PETSHARECODES}}
          PLANT_BEAN_SHARECODES: ${{ secrets.PLANT_BEAN_SHARECODES}}
          SUPERMARKET_SHARECODES: ${{ secrets.SUPERMARKET_SHARECODES}}
          DDFACTORY_SHARECODES: ${{ secrets.DDFACTORY_SHARECODES}}
          DREAM_FACTORY_SHARE_CODES: ${{ secrets.DREAM_FACTORY_SHARE_CODES}}
          JDZZ_SHARECODES: ${{ secrets.JDZZ_SHARECODES}}
          JDJOY_SHARECODES: ${{ secrets.JDJOY_SHARECODES}}
          BOOKSHOP_SHARECODES: ${{ secrets.BOOKSHOP_SHARECODES}}
          JD_CASH_SHARECODES: ${{ secrets.JD_CASH_SHARECODES}}
          JXNC_SHARECODES: ${{ secrets.JXNC_SHARECODES}}
          JDSGMH_SHARECODES: ${{ secrets.JDSGMH_SHARECODES}}
          JDGLOBAL_SHARECODES: ${{ secrets.JDGLOBAL_SHARECODES}}
          JD_BEAN_STOP: ${{ secrets.JD_BEAN_STOP}}
          JD_BEAN_SIGN_STOP_NOTIFY: ${{ secrets.JD_BEAN_SIGN_STOP_NOTIFY}}
          JD_BEAN_SIGN_NOTIFY_SIMPLE: ${{ secrets.JD_BEAN_SIGN_NOTIFY_SIMPLE}}
          PET_NOTIFY_CONTROL: ${{ secrets.PET_NOTIFY_CONTROL}}
          FRUIT_NOTIFY_CONTROL: ${{ secrets.FRUIT_NOTIFY_CONTROL}}
          JD_JOY_REWARD_NOTIFY: ${{ secrets.JD_JOY_REWARD_NOTIFY}}
          JOY_FEED_COUNT: ${{ secrets.JOY_FEED_COUNT}}
          JOY_HELP_FEED: ${{ secrets.JOY_HELP_FEED}}
          JOY_RUN_FLAG: ${{ secrets.JOY_RUN_FLAG}}
          JOY_TEAM_LEVEL: ${{ secrets.JOY_TEAM_LEVEL}}
          JOY_RUN_NOTIFY: ${{ secrets.JOY_RUN_NOTIFY}}
          JD_JOY_REWARD_NAME: ${{ secrets.JD_JOY_REWARD_NAME}}
          MARKET_COIN_TO_BEANS: ${{ secrets.MARKET_COIN_TO_BEANS}}
          MARKET_REWARD_NOTIFY: ${{ secrets.MARKET_REWARD_NOTIFY}}
          JOIN_PK_TEAM: ${{ secrets.JOIN_PK_TEAM}}
          SUPERMARKET_UPGRADE: ${{ secrets.SUPERMARKET_UPGRADE}}
          BUSINESS_CIRCLE_JUMP: ${{ secrets.BUSINESS_CIRCLE_JUMP}}
          SUPERMARKET_LOTTERY: ${{ secrets.SUPERMARKET_LOTTERY}}
          FRUIT_BEAN_CARD: ${{ secrets.FRUIT_BEAN_CARD}}
          UN_SUBSCRIBES: ${{ secrets.UN_SUBSCRIBES}}
          JDJOY_HELPSELF: ${{ secrets.JDJOY_HELPSELF}}
          JDJOY_APPLYJDBEAN: ${{ secrets.JDJOY_APPLYJDBEAN}}
          BUY_JOY_LEVEL: ${{ secrets.BUY_JOY_LEVEL}}
          MONEY_TREE_SELL_FRUIT: ${{ secrets.MONEY_TREE_SELL_FRUIT}}
          FACTORAY_WANTPRODUCT_NAME: ${{ secrets.FACTORAY_WANTPRODUCT_NAME}}
          JXNCTOKENS: ${{ secrets.JXNCTOKENS}}
          DREAMFACTORY_FORBID_ACCOUNT: ${{ secrets.DREAMFACTORY_FORBID_ACCOUNT}}
          JDFACTORY_FORBID_ACCOUNT: ${{ secrets.JDFACTORY_FORBID_ACCOUNT}}
